# Generated by Django 4.2.3 on 2023-07-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
            ],
        ),
    ]
